name: tensorflow-ci
dependencies:
  - python=3.6.9
  - pip
  - pip:
    - tensorflow==2.2.0rc1
    # - tf-nightly==2.2.0.dev20200327
    - tfdlpack
    - pytest
    - nose
    - numpy
    - cython
    - scipy
    - networkx
    - matplotlib
    - nltk
    - requests[security]
    - tqdm
